export const SLOWCHARGE_PAUSED_TO_SLOW_WATT_THRESHOLD = 800;
export const SLOWCHARGE_SLOW_TO_PAUSED_WATT_THRESHOLD = 4800;
export const SUNCHARGE_PAUSED_TO_SLOW_WATT_THRESHOLD = 300;
export const SUNCHARGE_PAUSED_TO_SLOW_INVERTER_THRESHOLD = 1100;
export const SUNCHARGE_SLOW_TO_PAUSED_WATT_THRESHOLD = 4000;
export const SUNCHARGE_SLOW_TO_PAUSED_INVERTER_THRESHOLD = 900;
